version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    networks:
        net:
    depends_on:
      - db
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "9001:9001"
      - "1883:1883"
    networks:
        net:    

  db:
    image: mysql:5.7
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: tSeriesDB
        MYSQL_USER: gustavo
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root 
    volumes:
        - persistent:/var/lib/mysql
    networks:
        net:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8080:80
    environment:
        MYSQL_USER: gustavo
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root 
    networks:
        net:
    depends_on:
      - db


volumes:
  persistent:

networks:
  net: